### ISSUE TITLE
Modify user via rest api

### ISSUE THREAD

**Issue by oscarminus** [ClusterCockpit/cc-backend#105]
Hi all,
perhaps i have overseen something, but is there a way to modify a user via the rest API? In special, i want to set the manager attribute on certain users per script. This issue refers to #83

**Comment by oscarminus** [comment]
Nevermind, i have found it ... The swagger.json in /api seems to be outdated.

**Comment by moebiusband73** [comment]
Hi,
the Swagger doc is not outdated. The current state is on purpose, the users endpoints are not meant to be exposed and only can be used in an authenticated admin session. It was added for the configuration view.

But if there is the need we could add this to the "official" REST API. The reason why we did not expose this rightaway is that changing user rights and properties is kind of security sensitive.
What do you think?
