### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by giesselmann** [ClusterCockpit/cc-backend#108]
Hi there,

I would like to ask for end-user documentation for cc.
Some questions users might have are related to coloring of plots, limits, filtering etc.

For admins, docs in markdown make sense, for users either a distinct doc page or an integrated solution would be good.

**Comment by spacehamster87** [comment]
We added a new project based on hugo and docsy here: https://git.clustercockpit.org/ClusterCockpit/cc-docs

It is available at https://www.clustercockpit.org/docs/
