### ISSUE TITLE
Documentation missmatch

### ISSUE THREAD

**Issue by oscarminus** [ClusterCockpit/cc-backend#12]
The folder ./utils/systemd contains only a README.md. According to this Readme, it should contain the systemd unitfile and a config.json too.

**Comment by moebiusband73** [comment]
Thanks for the notice.
The util directory is obsolete and its content was transferred to the Wiki.
You find the README and the required example files [here](https://github.com/ClusterCockpit/cc-backend/wiki/Systemd-Configuration).
