### ISSUE TITLE
Make metric selection and sorting in single job views configurable

### ISSUE THREAD

**Issue by moebiusband73** [ClusterCockpit/cc-backend#14]
Single job views should provide a UI to configure and sort the metric plots. This is then valid for all single job views of the same clusters.

**Comment by iamlouk** [comment]
UI-Wise, this is already implemented, see the `Metrics` button next to the `Manage Tags` UI element. What can still be improved here is that for now, all metrics are always fetched, even those not displayed/selected. Lazy loading them is what I am currently working on.
