### ISSUE TITLE
Switch from canvas to other plotting engine

### ISSUE THREAD

**Issue by spacehamster87** [ClusterCockpit/cc-backend#141]
Triggered by frontend reactivity dilemma in (Single-)User-View:

* Either, the plot adapts and canvas rerenders with every viewport change: Performace lag if heavy dataload
* Or, the plot is rendered with fixed dimensions: Non-Optimal overlap of rendered canvas' when viewport is reduced

Basic problem is: Canvas clears its contents as soon as dimensions are defined as variables and changed (i.e. viewport changes), and requires re-render of contents.

Proposed solution: Switch to different charting engine and rebuild histogram component from scratch (e.g. chart.js).

**Comment by moebiusband73** [comment]
Uplot also supports now barplots. It would be worthwhile to check this out.

**Comment by spacehamster87** [comment]
742c2e399e9db818eb80f7b735014970f03e6e53

**Comment by moebiusband73** [comment]
Update:
* Histograms can be implemented in uPlot
* The Polar plot requires chart.js
* * The custom roofline could also be implemented using uplot
