### ISSUE TITLE
Sync ldap user throws "ldap not enabled"

### ISSUE THREAD

**Issue by oscarminus** [ClusterCockpit/cc-backend#17]
Hallo, 

ich habe in der config.json die ldap-variablen gesetzt und in der .env ein benötigtes Passwort angegeben. Trotzdem sagt mir cc-backend -sync-ldap, dass ldap nicht aktiv wäre. Die Doku zu LDAP im Wiki ist leider nicht existent, laut README.md im config folder sieht die config korrekt aus. Fehlt noch irgendwo ein Schalter?

`        "ldap": {
                "url": "...",
                "user_base": "...",
                "search_dn": "...",
                "user_bind": "...",
                "user_filter": "...",
                "sync_interval": "1h",
                "sync_del_old_users" : false
        }
`

**Comment by iamlouk** [comment]
Also erstmal das vielleicht simpleste aber schon mögliches Problem: Du schreibst `cc-backend -sync-ldap`, das lädt ja aber die `config.json` gar nicht. Dafür brauchst du `cc-backend --config ./config.json --sync-ldap`. Falls es das ist und du es unituitiv findest das es nicht der default ist im aktuellen Verzeichniss von selbst nach einer `config.json` zu suchen können wir das ändern. Falls es das nicht ist:

Sorry, Doku schreibe ich noch (ich hab da aber Bezeichungen wie `search_dn` etc. alle vom alten PHP-ClusterCockpit übernommen falls das irgendwie hilft). Ich hab das LDAP-Zeugs schon länger nicht mehr getestet und musste mir deshalb selbst erstmal wieder ein Test-Setup zurechtbasteln, aber bei mir funktioniert alles mit der `config.json` von unten und [diesen](https://github.com/ClusterCockpit/cc-docker/blob/main/data/ldap/users.ldif) Testdaten.

```json
{
    "ldap": {
        "url": "ldap://localhost:389",
        "user_base": "ou=hpc,dc=rrze,dc=uni-erlangen,dc=de",
        "search_dn": "cn=admin,dc=rrze,dc=uni-erlangen,dc=de",
        "user_bind": "uid={username},ou=hpc,dc=rrze,dc=uni-erlangen,dc=de",
        "user_filter": "(&(objectclass=posixAccount)(uid=*))",
        "sync_interval": "24h",
        "sync_del_old_users": false
    }
}
```

@moebiusband73 , was wir vielleicht machen könnten wenn wir eh schon am refactoren sind und so: Im Moment gibt es ja drei Authentifizierungs-Möglichkeiten: Session-Cookies, JWTs und LDAP. Im Moment ist das alles in einem package und nicht trivial erweiterbar. Wir könnten vielleicht ein Interface `Authenticator` einführen, so ähnlich wie es ein Interface für die MetricDataRepositories gibt, damit andere Leute einfacher noch weitere Login-Möglichkeiten einbauen können, SSO oder so? Aber falls du das gut findest sollten wir dafür vielleicht lieber ein neues Issue aufmachen.

**Comment by oscarminus** [comment]
Es war in der tat die Angabe von -config. Ich bin davon ausgegangen, dass per Default die config.json im lokalen Verzeichnis genommen wird. Mit -config funktioniert es.

**Comment by iamlouk** [comment]
Ok, vielleicht ist es auch ein vernünftiger default eine ./config.json, falls sie existiert, automatisch zu laden, baue ich ein.

**Comment by moebiusband73** [comment]
A default config and a documentation of all options can be found here:
https://github.com/ClusterCockpit/cc-backend/tree/master/configs

But we need to add links from the wiki.
