### ISSUE TITLE
If user was authorized  with API role the web view does not work correctly

### ISSUE THREAD

**Issue by moebiusband73** [ClusterCockpit/cc-backend#179]
How to reproduce:
* Login with demo user
* Go to settings and assign api role and generate JWT token
* Authorize in Swagger UI using generated JWT token
* Logout from web session
* Query jobs endpoint (works)
* Try to login with same account to web interface
* Page ist not rendered correctly

The error reported logged:
<3>[ERROR]    /Users/jan/prg/cc-backend/web/web.go:118: Template error: template: home.tmpl:11:45: executing "content" at <.Roles.admin>: invalid value; expected auth.Role

**Comment by spacehamster87** [comment]
Removed Role-Check on "Not API Role" when loading valid roles for frontend render: Frontend now renders correctly for combined role users.
