### ISSUE TITLE
Job view for single node GPU jobs with only node level metrics fail to render

### ISSUE THREAD

**Issue by moebiusband73** [ClusterCockpit/cc-backend#180]
The job view for single node (and probably also) shared GPU accelerated jobs fail to render properly.

**Comment by spacehamster87** [comment]
Frontend will check if all requested accelerator metrics are `scope:accelerator` in the cluster configuration before fetching:
* If true, additionally fetch `accelerator` scope by default
* If one metric does mismatch, only load `node, (core)`

In the latter case, if metrics *do* have `accelerator` scope, it can still be fetched by using the `load more...` optin in the plot-scope dropdown.
