### ISSUE TITLE
Time format

### ISSUE THREAD

**Issue by giesselmann** [ClusterCockpit/cc-backend#181]
Hi,

I would like to suggest a change of the current time format in CC as it is sometimes very confusing.
Example 11:48 in CC is 11:48 in 24h format, but 12:48AM is 00:48. 
This is for both job-start time and configuration of filters counterintuitive. For filters it would also be easier to just enter a 24h format value.

Cheers,

Pay

**Comment by spacehamster87** [comment]
Hi there! Could you point to a specific example via link to the view, a way to reproduce, or a screenshot?

As far as I am concerned, the 24-Hour format is already in use for filters and display of starting times, as I can not see a way to change to AM/PM format locally or at out live system. Might be a case of the individual browsers locale perhaps?

**Comment by giesselmann** [comment]
Hmm, that's funny, for me it looks like this:
![image](https://github.com/ClusterCockpit/cc-backend/assets/20906873/0a285adf-3777-4da6-816c-ffbf8251769b)
and
![image](https://github.com/ClusterCockpit/cc-backend/assets/20906873/3a03c441-16b8-4873-9dce-558c398fab42)

And you're right, if I go to https://www.localeplanet.com/support/browser.html
I get 
```
date.toLocaleDateString(): 7/17/2023
date.toLocaleTimeString(): 4:37:22 PM
date.toLocaleString(): 7/17/2023, 4:37:22 PM
date.toUTCString(): Mon, 17 Jul 2023 14:37:22 GMT
```

I was sure, the website would make this decision, will check my local config...
