### ISSUE TITLE
Enhancement: Display admin notifications 

### ISSUE THREAD

**Issue by giesselmann** [ClusterCockpit/cc-backend#185]
Hi,

I have a low-prio enhancement idea: Would it be possible, to display notifications for all users e.g. a banner below the top navigation panel? 
Background: after a maintenance we had some problems with job-imports and it would be great to inform users not via Mail but directly on the page. Could also be used to announce updates/downtimes etc.

Implementation could be a background thread reading `./var/notify.txt` periodically and updating a config field with the content.
Would be easy to control as `echo hi users > ./var/notify.txt`

**Comment by moebiusband73** [comment]
Would it be sufficient to show the banner on the homepage, means the page with the cluster list at the top?
I would not need a background thread. I can just check if the file exists on every homepage render and then enable a banner in the template in case it does.

**Comment by giesselmann** [comment]
Yes!
Anything that is not on the login page since users might be logged in for quite a while.
Thanks!
