### ISSUE TITLE
html code displayed after logout

### ISSUE THREAD

**Issue by oscarminus** [ClusterCockpit/cc-backend#19]
Nach dem Logout wird statt der Webseite deren HTML-Code im Chrome angezeigt. Firefox möchte die Webseite sogar speichern und zeigt als Content-Type "application/octet-stream" an.

**Comment by iamlouk** [comment]
I was not able to reproduce this with Mozilla Firefox 101.0.1 or Chromium 103.0.5060.53, but indeed the Content-Type Header was missing for the logout response. I hope the change I just made fixes the behaviour.

**Comment by oscarminus** [comment]
Yes it does. Thank you.
