### ISSUE TITLE
Add job footprint as a svelte component

### ISSUE THREAD

**Issue by moebiusband73** [ClusterCockpit/cc-backend#196]
Apart from the polar plot the aggregate performance of a job is not shown.
Add a component that renders an overall job footprint including energy consumption.
It might be required to extent the db schema.
It has to be configurable which metrics are used.

**Comment by spacehamster87** [comment]
Some questions for preparation / discussion:

* Use footprint-component as ...
  * additional card above job metric plots, enabled / disabled by default?
  * alternative to polar plot / roofline / or both?
  * enabled / switched via button or similar
* In addition to all available metric averages, which additional info is useful?
  * E.g., energy consumption (duration * avg. wattage) is mentioned in opening post

**Comment by spacehamster87** [comment]
[Branch 196_add_footprint](https://github.com/ClusterCockpit/cc-backend/tree/196_add_footprint)

* Adds footprint component
  * Renders base metric averages as colored bars respective to configured threshold values
  * Rendered metrics dependent on job and cluster
    * CPU Metrics (Exclusive): cpu_load, flops_any, mem_used, mem_bw
    * CPU Metrics (Shared): cpu_load, flops_any, mem_used
    * GPU Metrics (Exclusive): cpu_load, flops_any, acc_utilization, mem_bw
    * GPU Metrics (Shared): cpu_load, flops_any, acc_utilization
  * Metric-Threshold configs for sublucsters are used when found 
  * Metric-Thresholds are scaled for shared jobs
    * `cpu_load` maximum is number of allocated cores
    * `aggregation:sum` metric thresholds are scaled down based on number of allocated cores
* Component always rendered in job-view
* Component optional in job-list, activated in "Metrics" selector
  * Selection saved for User and Cluster
* Additionally, new fields are requestable from GraphQL, read from jobs' DB entry
  * ´flopsAnyAvg, memBwAvg, loadAvg´

**Comment by spacehamster87** [comment]
Merged
