### ISSUE TITLE
Offer continuous scroll as alternative to paging for job lists

### ISSUE THREAD

**Issue by moebiusband73** [ClusterCockpit/cc-backend#20]
Currently for the job lists a classic paging UI is used for long job lists.

Also support continuous scrolling for job lists.
A part of this is to change the GraphQL paging API from offset paging to cursor paging.

**Comment by spacehamster87** [comment]
New config option in config.json: `"job_list_usePaging": true"

Implemented infinite scroll as optional job list handling - default value maintains classic paging.
