### ISSUE TITLE
Allow for alternative layouts and compositions for job list rows

### ISSUE THREAD

**Issue by moebiusband73** [ClusterCockpit/cc-backend#21]
Currently the job lists show the Meta-Data on the left and a row with metric timeseries plots on the right.

Allow to specify and configure alternative views as e.g. Job metric statistics, a traffic light based system, and/or a polarplot.

**Comment by spacehamster87** [comment]
#196 

* Optionally displayed in jobList-Row
* Selection saved per user and cluster
* Displays basic metric averages, colored in respect to configured thresholds (alert, caution, nornal, peak)
* Additionally displays colored icons and tooltip with further information
