### ISSUE TITLE
Missing core in cluster.json in Demo Archive

### ISSUE THREAD

**Issue by aw32** [ClusterCockpit/cc-backend#216]
In the file `var/job-archive/alex/cluster.json` in the `topology` attribute for the partitions on the `core` level the core with hwthread `72` is missing.

```
[
    71
],
[
    73
],
```

**Comment by moebiusband73** [comment]
Thanks for the notice.! There where also a lot of MacOs system files included in the tarball.
I fixed the missing core items. Let me know in case I missed something.
