### ISSUE TITLE
Provide initial values for range filter UI

### ISSUE THREAD

**Issue by moebiusband73** [ClusterCockpit/cc-backend#224]
Currently in all range filter UIs always upper and lower limit have to be set.

Allow to only set one limit.

**Comment by spacehamster87** [comment]
bf64fc5213729673eff19a24f5c694b4419bfe27

* Duration filter: Added `More than` and `Less than` fields, changed existing field to `duration between`
* StartTime filter: Pre-filled fields with dates "a month ago" (to the minute) and "now", for "from" and "to" selections, respectively
