### ISSUE TITLE
No Data in Statistics Table

### ISSUE THREAD

**Issue by giesselmann** [ClusterCockpit/cc-backend#229]
There seems to be a bug within the statistics table, for some jobs although all metrics are present, no statistics are displayed.
At least on our side it seems to be the case for single node jobs only.

Version is 1.2.2 a5b29f4

**Comment by spacehamster87** [comment]
https://github.com/ClusterCockpit/cc-backend/commit/aac3e7d2f4c458cab73ae8a8fcf933c0b42a9aff

On hotfix branch:

* Fixed defect logic on scope auto-select for statstable
* Added socket scope to auto-load and auto-select if available for single node jobs
* Removed auto-disable of scope selector

**Comment by giesselmann** [comment]
Deployed in test system, looks good :+1:
