### ISSUE TITLE
Metric Plot y-limit

### ISSUE THREAD

**Issue by giesselmann** [ClusterCockpit/cc-backend#235]
Hi,
I think there's an issue with the y-limit of metric plots, given a config of some bandwith e.g.
`      
"peak": 12.5,
"normal": 0.5,
"caution": 1,
"alert": 2
`
The scaling of plots stops at around 5.
Looks like some hard limit to me. Haven't checked the code, but the y-axis limit should imo be either data dependent (expensive) or sth. like max(peak, 5*normal) + 10%

**Comment by spacehamster87** [comment]
HI there,

actually, you are, or better, were right: It *was* `normal * 10` for the `maxY` value of metric plots - Which is also the reason for your plot ending at a value of 5.  Alas, we recently merged two pending pull requests, which changed the limit to `peak * 10` ([see here](https://github.com/ClusterCockpit/cc-backend/blob/2d8cf02296ec42c4466beef1c54c97c44779ec1a/web/frontend/src/plots/MetricPlot.svelte#L165)).

If this still causes problems with metric readout, feel free to re-open this ticket!
