### ISSUE TITLE
User Authentication using Keycloak or any OpenID client for using external auth providers such as LDAP , github ,google .....

### ISSUE THREAD

**Issue by sanjay7178** [ClusterCockpit/cc-backend#236]

**Comment by moebiusband73** [comment]
Could you be more specific. Currently cc-backend support authentication via local accounts (stored in database), LDAP directory, and via JWT tokens.

You want support for OAuth2 to use then something like Keycloak to relay to any external authentication provider?
Adding support for authentication via OAuth2 should be not too difficult.

**Comment by sanjay7178** [comment]
yeah !!
