### ISSUE TITLE
GPU id label in job view statistic table is always the same on multi GPU jobs

### ISSUE THREAD

**Issue by moebiusband73** [ClusterCockpit/cc-backend#239]
<img width="1082" alt="Screenshot 2024-02-13 at 11 44 25" src="https://github.com/ClusterCockpit/cc-backend/assets/11572749/56ef3bf8-e6f7-4e32-912c-e67001f0f716">

**Comment by spacehamster87** [comment]
It seems not to be a frontend-bug, as it just returns what was delivered by the backend api, see

![apiresult_accids](https://github.com/ClusterCockpit/cc-backend/assets/83573843/b5d58b73-3ffc-419e-8a93-005271fefe4c)
