### ISSUE TITLE
Provide a configurable  map for any hardcoded metric used in implementation

### ISSUE THREAD

**Issue by moebiusband73** [ClusterCockpit/cc-backend#260]
Currently at several places metric names are hardcoded. This breaks if the metric is missing or the user configured it with a different name.

Solution:
Provide a lookup map that can be configured by the user and replace any hardcoded metric name with a check in the lookup map.

**Comment by spacehamster87** [comment]
In this specific case (`JobFootprint`) we need four configurable arrays to allow for the following cases:

* Metrics in Footprint for Exclusive CPU Jobs
* Metrics in Footprint for Shared CPU Jobs
* Metrics in Footprint for Exclusive GPU Jobs
* Metrics in Footprint for Shared GPU Jobs

That being said, four metrics (`cpu_load, flopy_any, mem_bw, mem_used`) still will be required by name, for the following reasons:

* `cpu_load, flopy_any, mem_bw,`: Averages of these metrics are persisted in the SQLite DB and will be queried first from there.
* `mem_used`: Logic is *inverted* for Footprint and has to be handled specifically -> The smaller the value, the better; This is defined in the metric thresholds.
