### ISSUE TITLE
Display Message of the Day on startpage

### ISSUE THREAD

**Issue by oscarminus** [ClusterCockpit/cc-backend#273]
We currently have no way of directly informing ClusterCockpit users about upcoming maintenance work in the CC. It would be good if the admin could set a Message of the Day, which would then be displayed on the login screen and below the menu bar after login.

**Comment by giesselmann** [comment]
Not documented, but `.var/notice.txt` will be displayed as a banner after login.

**Comment by oscarminus** [comment]
Thanks, that fits the request for 90% The disadvantage of this is, that you have to have root access on the machine which is running cc-backend. With an "config option" inside the admin page, all CC-Admins could set such a notice. But in fact, with this possibility the priority of my request becomes very low.

**Comment by moebiusband73** [comment]
I have to discuss, but I think adding the option to write this file from the settings view for admins should be not difficult.
And of course we have make it more clear in the documentation this is available at all.

It is mentioned here: https://clustercockpit.org/docs/tutorials/customization/ but maybe not prominently enough or with the wrong heading.

**Comment by spacehamster87** [comment]
Pushed to dev: Simple Text Form Field in Admin-Settings will write content to notice.txt. Updating with empty field will remove splash box from homepage.
