### ISSUE TITLE
Introduce tag scope

### ISSUE THREAD

**Issue by moebiusband73** [ClusterCockpit/cc-backend#275]
Currently tags are globally visible. Everybody including regular users can see all tags.

It would be useful if tags set by users are restricted to one user and globale tags are not visible to regular users.

A possible implementation would add a column scope which is then either global oder a user_id. For a regular user only his own tags are shown.
The scope column can be set implicitly by considering the highest role.

**Comment by spacehamster87** [comment]
* New column `scope`in tag table
* Value is String with one of three (for now) classes
  * `$Username`: The username of the user creating the tag, equivalent to `Private`, thus only visible to the user
  * `global`: Tags visible for everyone, e.g. auto-tagged software tags via API
  * `admin`: Tags visible for administrative staff only (roles `admin, support`), e.g. tags relating to job health
* Creating tags in the interface
  * `User` role users will see no difference, tags will automatically be private in scope
  * `Admin` role users will see an additional selector, allowing to select the scope of the new tag (Defaults to Private)
* Creating tags via API
  * `type ApiTag` now includes field for scope of new to be created tag
* Visibility of Tags
  * Tag scopes are colored differently
  * Tags will be filtered by scope befor ebeing delivered to filter component, tags view and tagManagement modal
