### ISSUE TITLE
Display final job state

### ISSUE THREAD

**Issue by oscarminus** [ClusterCockpit/cc-backend#28]
Ich hätte eine Verbesserung am Frontend:

Aktuell werden laufende Jobs entsprechend in der Jobliste gekennzeichnet. Für einen Überblick wäre es gut, wenn grundsätzlich immer der aktuelle Status des Jobs angezeigt wird. Also nach Beendigung auch "Success", "Failed", ...

Diese Anzeige sollte dann in der Jobliste und in der Job-Detailansicht sichtbar sein.

**Comment by iamlouk** [comment]
As it currently is, a green badge is shown for "running" jobs, no badge is shown for "completed" jobs and a red badge is shown for all other job states. This means that if there is no coloured badge at all, you can be sure that the job is in the "completed" state.
