### ISSUE TITLE
Login to web interface broken with current 1.4.0 rc/ master branch

### ISSUE THREAD

**Issue by behnle** [ClusterCockpit/cc-backend#301]
Dear ClusterCockpit developers,
with the current master branch, no login to the web interface is possible anymore.
Instead, the log of the cc-backend shows the following contradictory log:
<pre>
[root@clustercockpit-clone cc-backend]# ./cc-backend -server -dev -loglevel debug
<7>[DEBUG]    SQL query 
        CREATE TABLE IF NOT EXISTS schema_migrations (version uint64,dirty bool);
  CREATE UNIQUE INDEX IF NOT EXISTS version_unique ON schema_migrations (version);
   []
<7>[DEBUG]    Took: 24µs
<7>[DEBUG]    SQL query SELECT version, dirty FROM schema_migrations LIMIT 1 []
<7>[DEBUG]    Took: 12.47µs
<6>[INFO]     auth.go:104: Missing LDAP configuration: No LDAP support!
<6>[INFO]     jwtSession.go:39: JWT Session authenticator successfully registered
<7>[DEBUG]    environment variable 'CROSS_LOGIN_JWT_PUBLIC_KEY' not set (cross login token based authentication will not work)
<6>[INFO]     auth.go:122: jwtCookieSessionAuth init failed: No JWT cookie login support!
<6>[INFO]     archive.go:93: Load archive version 2
<6>[INFO]     updateFootprintService.go:29: Register Footprint Update service with 10m interval
<6>[INFO]     updateDurationService.go:23: Register Duration Update service with 5m interval
HTTP server listening at 172.0.100.102:8080...<7>[DEBUG]    SQL query SELECT password, ldap, name, roles, email, projects FROM hpc_user WHERE hpc_user.username = ? ["demo"]
<7>[DEBUG]    Took: 111.24µs
<7>[DEBUG]    Can login with user &{demo $2a$10$m5AHpRpXPx2UzOOg2Hnj7e1/nC.K2RX1/KGJ4iOkQSrd8okSlDBz6   [admin] [] 0 0}
<6>[INFO]     auth.go:238: login successfull: user: "demo" (roles: [admin], projects: [])
<7>[DEBUG]    POST /login (302, 0.02kb, 60ms)
<6>[INFO]     auth.go:279: auth -> authentication failed
<7>[DEBUG]    Page config : map[]
<7>[DEBUG]    GET / (401, 1.22kb, 1ms)
<7>[DEBUG]    GET /global.css (200, 0.48kb, 7ms)
<7>[DEBUG]    GET /uPlot.min.css (200, 0.76kb, 7ms)
<7>[DEBUG]    GET /bootstrap-icons.css (200, 13.01kb, 11ms)
<7>[DEBUG]    GET /build/header.js (200, 29.80kb, 8ms)
<7>[DEBUG]    GET /bootstrap.min.css (200, 30.06kb, 15ms)
<7>[DEBUG]    GET /img/logo.png (200, 15.67kb, 0ms)
</pre>
i.e.
- the user is found
- login is succesful
- but the subsequent authentication somehow fails

Steps to reproduce:
1. Clone the current master branch (tested with ab284ed208e284d842c83fc48664467ba73ac90e)
2. Start the demo to download the sample job archive, create the "demo" user
3. Kill the demo script, configure the desired IP adress, relaunch the backend with `-server -dev -loglevel debug`

The same procedure with the 1.3.1 release works flawlessly.

I did not try to figure out the root cause, maybe some token is missing after login.

**Comment by moebiusband73** [comment]
Thank you for the report.
We can reproduce it: It always works if you enter localhost in your Browser, it does not work anymore if you use a IP address.
You are right this worked with the older release that was go 1.18 and also an older Gorilla Session package version. When I rebuild the release 1.3.2 code  with a recent golang version and upgrade the Gorilla Session package to the most recent version it also does not work anymore there.
So we suspect the default handling for setting cookies got stricter and that it does not work with a raw IP address. We will further try to clarify. Until then for testing use localhost.

**Comment by moebiusband73** [comment]
OK, there are now further insights. As it seems the defaults for Cookie settings have changed. And IP or domain actually does not matter.

Now a secure context is required.
This are the current defaults:
![image](https://github.com/user-attachments/assets/9f2ef581-9ecc-42ab-b26a-ef91e8290324)

If you set Secure to false, it also works with an IP and without TLS again.
I will set the SameSite  Option to StrictMode which means no Third Party Cookies but keep the Secure setting. This means you have to use localhost for local testing from now on.

**Comment by moebiusband73** [comment]
I decided to solve it by checking if https is configured and if not the Secure Option is set to false.
This means it will behave as bevor. I will push a fix soon.

**Comment by behnle** [comment]
Thanks for fixing. It currently works without TLS again, but i will try to set up proper transport encryption ASAP.
