### ISSUE TITLE
Allow specification of hosts in cluster.json with pattern matching

### ISSUE THREAD

**Issue by TomTheBear** [ClusterCockpit/cc-backend#39]
Instead of specifying the exact host names, some kind of pattern matching would be helpful. Either with the SLURM nodelist format `ws0[000-100]` or with Golang regular expressions.

**Comment by moebiusband73** [comment]
This is already fixed.
Allowed are lists with ranges and lists of ranges. We do not support all of the Slurm syntax though.
Example:
* ws03[01-99,102-132],ws04[10-88]
