### ISSUE TITLE
Initialize required infrastructure without user intervention

### ISSUE THREAD

**Issue by moebiusband73** [ClusterCockpit/cc-backend#41]
Currently the var directory and enclosed job.db file have to be created by hand. Let cc-backend create required files itself on initial start.

**Comment by spacehamster87** [comment]
@moebiusband73 

With implementation of database migration "from zero" and makefile setup: Are there any other "manual" steps left to be performed by the user on initial setup? I can not think of any, so this Ticket could be closed.
