### ISSUE TITLE
Failed to launch the demo due to 'UNIQUE constraint failed: user.username'

### ISSUE THREAD

**Issue by weijianwen** [ClusterCockpit/cc-backend#56]
I started `./startDemo.sh` but failed in the following error:

```
<3>[ERROR]   UNIQUE constraint failed: user.username
```

This issue can be reproduced on both Mac OS X and Debian Linux. Any suggestion? Thank you!

**Comment by moebiusband73** [comment]
Hi, this is an issue if you use the startDemo script  multiple times. It will try to create a user that already exists in the database. I added a check if ./var already exists and skip initialization in that case. I also fixed the other errors in the script.
