### ISSUE TITLE
Replace git@ URL with https:// in README

### ISSUE THREAD

**Issue by weijianwen** [ClusterCockpit/cc-backend#58]
I suggest to clone the repo with https instead of SSH in README, which help users without SSH key settings on GitHub. For these users, cloning via SSH results in a `git@github.com: Permission denied` error.

Replacing

```
git clone git@github.com:ClusterCockpit/cc-backend.git
```

with 

```
git clone https://github.com/ClusterCockpit/cc-backend.git
```

solves this issue.

**Comment by moebiusband73** [comment]
I changed the URLs to the repo in the README to https:// .
