### ISSUE TITLE
Dash outside [] not possible in nodelist in cluster.json

### ISSUE THREAD

**Issue by oscarminus** [ClusterCockpit/cc-backend#59]
Our noctua 1 cluster has nodenames with dashes inside, for example "cn-0010". cc-backend denies these nodenames inside the node list in the subcluster definition. 

[ERROR]   in noctua1/cluster.json: node list: invalid character: 45

**Comment by moebiusband73** [comment]
I added a patch in branch bug-59-nodelist-dash
Can you please test if this works for you?

**Comment by moebiusband73** [comment]
One thing that does not work is anything apart a range within [].
Eg cn-00[10-15,20]  will not work.

**Comment by moebiusband73** [comment]
Another note: I think that the token based parser is a bit over-engineered in this case. Maybe it would make sense to replace it by a simpler split and match based solution.
