### ISSUE TITLE
InfluxDB unusable: config option checks contradict

### ISSUE THREAD

**Issue by fodinabor** [ClusterCockpit/cc-backend#60]
I just tried setting up cc-backend in conjunction with InfluxDB and was not able to start the backend when setting `metricDataRepository`->`kind` to either `influxdb` or `influxdb-v2` as there's two contradicting checks.

First, there is `influxdb-v2` https://github.com/ClusterCockpit/cc-backend/blob/master/pkg/schema/schemas/config.schema.json#L141 which is validated upon startup.
Secondly, the metricdata dispatch looks for `influxdb`: https://github.com/ClusterCockpit/cc-backend/blob/master/internal/metricdata/metricdata.go#L56

Not sure which version should be preferred (I dirty patched the schema to use `influxdb`).

Edit: yeah okay.... seems most views are unimplemented with InfluxDB. Does this mean, the currently most stable metric store is cc-metric-store?

**Comment by moebiusband73** [comment]
Yes, at the moment you should stick with cc-metric-store or use a proxy to push stuff to cc-metric-store as the metric cache for cc-backend. cc-metric-store is just a short term metric in-memory cache and can co-exist with a long-term TS database.

I will have a look at the validation issue.  There was a V1 client, it seems people still stick with InfluxDB V1 even if it is really old by now.

**Comment by moebiusband73** [comment]
I also added a comment in the README that the only tested and supported setup at the moment is using cc-metric-store.
