### ISSUE TITLE
How to generate job-archive file

### ISSUE THREAD

**Issue by Autumn-Roy** [ClusterCockpit/cc-backend#61]
I want to know, how to generate the job-archive files like the demo. I tried to use cc-metric-collector as information gathering, but it seems can ‘t generate a job-archive file, so it can't display by cc-backend.

**Comment by moebiusband73** [comment]
Hi,
to setup the job archive is part of the configuration. You need to create a directory for each cluster and setup the cluster.jsob file within it to describe the processor and metrics you want to see. Did you already do the hands-on in the source tree ./docs directory?
I am sorry for the currently poor documentation of the overall setup. The basic setting is: the cc-metric-collector will run as node-agent on every node and collect metrics. Those metrics are then send to the cc-metric-store. There has to be an integration with your job scheduler to get the job meta data. This is implemented using a REST API provided by cc-backend. You can play with the REST API using a Swagger UI if you start cc-backend in dev mode. cc-slurm-sync is just an example how this could be done. The main problem is that the resources a job uses (extracted from your job scheduler) must match those used in cc-metric-collector/cc-metric-store. This is simple as long as you only have node lists, but becomes cumbersome as soon as you have shared jobs or jobs using GPUs. In the future we plan to integrate the support for slurm (using its REST API) into cc-backend. Till then you have to write a script that provides the job meta data. I hope this helps.

**Comment by Autumn-Roy** [comment]
> 
Thank you for answering my question. Can I setup the whole ClusterCokcpit like this? In every cluster node, install cc-metric-collector to collect metrics; Install cc-metric-store and cc-backend on a separate node to receive the metrics.
When the metrics stored on cc-metric-store/var/checkpoints/<cluster name>, I have to use my own script to collect and generate the matched job meta data.  Is it right?

**Comment by moebiusband73** [comment]
Yes that is correct. This piece of documentation for the big picture is still missing :-(.
You have to extract the job meta data and communicate it to cc-backend using the Job REST API.
In the long term we plan to integrate a Slurm Job Scheduler adapter in cc-backend. Getting all the required information out of Slurm is not trivial, especially with node sharing. There is an example script in https://github.com/ClusterCockpit/cc-slurm-sync. Maybe that helps.
