### ISSUE TITLE
MySQL command CAST(xx as int) should be CAST(XX as SIGNED)

### ISSUE THREAD

**Issue by Autumn-Roy** [ClusterCockpit/cc-backend#67]
My database is MySQL 8.0.30. When I want to check the users, there is an error for me: 
` [GraphQL] Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'int), CAST(ROUND(SUM(job.duration * job.num_nodes * 2 * 10) / 3600) as int) FROM' at line 1`
Then I search the command of MySQL, the datatype of CAST function don't have "int", but only "signed" and "unsigned". So I change the command and it works. Likely, `CAST(xx as int) ` is used in SQL server.

**Comment by moebiusband73** [comment]
Hi,
we use mostly sqlite: https://www.sqlite.org/datatype3.html.
Kind of strange that you cannot use the standard types in the CAST function.
Unfortunately sqlite only support integer (signed).
I guess we have to check the database driver configured in the code and choose a different query for mysql.
Or do you have another suggestion?

**Comment by moebiusband73** [comment]
It took a while but I now added the backend driver type and adopt the expression according to the backend.
For type mysql I now use `CAST(xx as unsigned)`. Is this what you also did by hand?
