### ISSUE TITLE
Job view dies if `mem_bw` metric not available

### ISSUE THREAD

**Issue by fodinabor** [ClusterCockpit/cc-backend#70]
Related to #69 - for some reason `mem_bw` is not provided by the `/{job-id}?metric=flops_any&metric=mem_bw&...` request made when loading both, the job list as well as the job view.

When this happens, the whole page is stuck and does not allow clicking anything anymore.
The dev console prints the following error:
```
job.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'metric')
    at Array.J$ (job.js:1:334161)
    at u (job.js:1:536)
    at ko (job.js:1:55798)
    at We (job.js:1:10469)
    at new Oo (job.js:1:57102)
    at Array.Y$ (job.js:1:332872)
    at Object.p (job.js:1:335026)
    at p (job.js:1:894)
    at Object.p (job.js:1:132543)
    at ke (job.js:1:6235)
```

I guess [the roofline plot](https://github.com/ClusterCockpit/cc-backend/blob/e00e3208caefbba05cd19151a524b09cc0d41bce/web/frontend/src/Job.root.svelte#L118] just assumes that there's always a `mem_bw` metric (hardcoded :-() and thus has an invalid access there when it's not there.

**Comment by moebiusband73** [comment]
We also had issues with hanging views. And I also suspected that the access to the roofline metrics is hardcoded is the reason.
We will have a look at it.

**Comment by spacehamster87** [comment]
Moved `.metric` selection from Job-Root to Roofline-Component: Roofline now renders even if `mem_bw` and/or `flops_any` are missing. 

Browser-Console logs more comprehensible errors. Analysis-View and Status-View unaffected by changes.
