### ISSUE TITLE
Improve Systems View

### ISSUE THREAD

**Issue by fodinabor** [ClusterCockpit/cc-backend#71]
- [ ] It would be great if the systems view would also show the units the graphs are in.
- [x] The x-axis ticks are confusing. They show e.g. 0 to 30min, but should rather show the timestamps or -30 to 0min as this is a "live" view and not the runtime of a job that has a fixed starting point.
- [x] Simplify "live monitoring": Either actually introduce live polling or likely, simpler: URL encode selected options (time, metric, node filter), so that reloading the page shows the same but updated results

**Comment by moebiusband73** [comment]
I agree with both points.
With regard to the x-axis the best solution would probably be to show the time. What do you think?

**Comment by fodinabor** [comment]
Sounds good to me as well. 👍🏼

**Comment by fodinabor** [comment]
Also: Simplify "live monitoring": Either actually introduce live polling or likely, simpler: URL encode selected options (time, metric, node filter), so that reloading the page shows the same but updated results

**Comment by spacehamster87** [comment]
Metric units can be found either in the metric-selector for the whole system view, or in the plot titles in single-node view.
