### ISSUE TITLE
How to estimate the memory use of cc-metric-store

### ISSUE THREAD

**Issue by Autumn-Roy** [ClusterCockpit/cc-backend#84]
We want to use clustercockpit to monitor the cluster with 3000 nodes. Now the seperate machine installing clustercockpit is 8Gb memory. When the cc-metric-store start, the memory use of this machine will reach 90% or above, then it killed by system. To resolve this problem, we want to increas memory of machine, but we don't know the much memory is enough.

Is there a recommanded memory of our project?

The config of cc-metric-store is below:
> numbers of nodes: 3000
> numbers of metrics: 100+
> "checkpoints" interval: 12h
> "checkpoints" restore: 24h
> retention-in-memory： 24h

**Comment by moebiusband73** [comment]
We migrated this issue to the cc-metric-store repo:
https://github.com/ClusterCockpit/cc-metric-store/issues/17

Sorry for the delayed answer. We will address this soon, maybe by providing a script.
