### ISSUE TITLE
error in swagger definition

### ISSUE THREAD

**Issue by Armagetron** [ClusterCockpit/cc-backend#95]
There is an error in the swagger definition that causes problems in certain languages like java. The return value of `api/jobs` is not just a an array of schema.Job but it is an object that has the property jobs, which is an array of schema.Job.

Instead of
```
"200": {
    "description": "Array of matching jobs",
    "schema": {
        "type": "array",
        "items": {
            "$ref": "#/definitions/schema.Job"
        }
    }
},
```
the swagger file should look like this
```
"200": {
    "description": "Array of matching jobs",
    "schema": {
        "type": "object",
        "properties": {
            "jobs": {
                "type": "array",
                "items": {
                    "$ref": "#/definitions/schema.Job"
                }
            }
        }
    }
},
```
Since the swagger file is automatically generated, the fix should be somewhere else.

**Comment by moebiusband73** [comment]
Thanks for your report!
Can you please test if the recent changes fixes your issues.

**Comment by Armagetron** [comment]
I tested version 1fc090965d70ca3e78fabbd557f13f4157499256. Python works fine. Java however has some problems. The class AllOfschemaJobMetaJobState which inherits from the enum SchemaJobState. Enums are not meant to be extended.

**Comment by moebiusband73** [comment]
I made a small change. The enum was from a swagger comment. In the code there is no inheritance (there is no such thing in Golang) and also no extension of the enum.
Can you try if this fixes your problem.

**Comment by Armagetron** [comment]
Ok, I cannot get it to work. The problem is the
```
"allOf": [
                        {
                            "$ref": "#/definitions/schema.JobState"
                        }
                    ],
```
part. This creates the dependency and java cannot handle that.

**Comment by moebiusband73** [comment]
That part is generated by swagger.
Did you try how the swagger.json should be so that it works? I mean you can just edit the swagger file and check if it works.

For example maybe the x-enum-varnames is the problem.
I do not know the specification for the API spec. Maybe there is an alternative to allOf?

**Comment by moebiusband73** [comment]
I searched around in the internet and did not found a simple solution.

We use this generator: https://github.com/swaggo/swag
I guess the main issue is the allOf .  I think this is a bug in swag . The datatype is correctly detected as enum but it handles it in composable data structures as a collection of objects.

I fear there is no simple solution to this. I can open a ticket at swag and ask what they think of this.

**Comment by moebiusband73** [comment]
What you can try is to replace all references to jobState with the following json:

            "description": "Final state of job",
            "type": "string",
            "enum": [
                "completed",
                "failed",
                "cancelled",
                "stopped",
                "out_of_memory",
                "timeout"
            ]

And see if this fixes it. In my opinion this is what should be generated.

**Comment by moebiusband73** [comment]
It seems there is no easy fix.
The missing enum type in golang cannot be easily handled by some code generators.
So I will close this ticket for now.
